import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Gaza",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="shortcut icon" href="/static/pngegg.png" />
      </Head>
      <body className={inter.className}>
        <Header />
        <main className="main-layout">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
